### ISSUE TITLE
viewbinding异常，是不兼容吗

### ISSUE THREAD

**Issue by zhongcg** [CoderAlee/PaintedSkin#10]
运行报错，异常信息
E/ThemeSkin: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at org.alee.component.skin.factory2.ViewInflater.createView(ViewInflater.java:108)
        at org.alee.component.skin.factory2.BaseFactory2.onCreateView(BaseFactory2.java:39)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)

**Comment by zhongcg** [comment]
找到问题了。初始化代码顺序不对

**Comment by zhongcg** [comment]
Caused by: java.lang.reflect.InvocationTargetException 这些异常看不出来是哪些view无法加入换肤，该如何解决这些异常
