### ISSUE TITLE
textColor 资源找不到

### ISSUE THREAD

**Issue by zhongcg** [CoderAlee/PaintedSkin#15]
E/ThemeSkin: android.content.res.Resources$NotFoundException: File res/color/black_primary.xml from ComplexColor resource ID #0x7f060026
  at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:927)
        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:756)
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:835)
        at android.content.res.Resources.getColorStateList(Resources.java:993)
        at org.alee.component.skin.pack.StandardSkinResourcesProvider.getColorStateList(StandardSkinResourcesProvider.java:42)
        at org.alee.component.skin.pack.BaseStandardSkinResourcesProvider.getColorStateList(BaseStandardSkinResourcesProvider.java:92)
        at org.alee.component.skin.pack.BaseSkinResourcesProvider.getColorStateList(BaseSkinResourcesProvider.java:63)
        
xml中设置textColor 报错找不到文件
我在皮肤包里都已经放了，就是找不到。
也试过ThemeSkinService.getInstance().currentThemeSkinPack.getColorStateList() 一样找不到

求大神帮忙看看

**Comment by zhongcg** [comment]
好吧 问题找到了，因为没有在皮肤包下定义color id，我以为只要皮肤module里通过依赖方式引入也可以。结果不行。 要再次声明id
