### ISSUE TITLE
未能成功创建

### ISSUE THREAD

**Issue by zhongcg** [CoderAlee/PaintedSkin#16]
未能成功创建 [ androidx.appcompat.widget.AppCompatTextView ] 

2021-12-01 08:42:28.964 29117-29117/com.chindeo.nursehost E/ThemeSkin: android.view.InflateException: Binary XML file line #84: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at org.alee.component.skin.factory2.ViewInflater.createView(ViewInflater.java:108)
        at org.alee.component.skin.factory2.BaseFactory2.onCreateView(BaseFactory2.java:39)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.lazylibs.component.ui.fragment.BaseSupportDialogFragment.onCreateView(BaseSupportDialogFragment.java:35)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at androidx.appcompat.widget.TintContextWrapper.shouldWrap(TintContextWrapper.java:79)
        at androidx.appcompat.widget.TintContextWrapper.wrap(TintContextWrapper.java:46)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:102)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:97)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at org.alee.component.skin.factory2.ViewInflater.createView(ViewInflater.java:108) 
        at org.alee.component.skin.factory2.BaseFactory2.onCreateView(BaseFactory2.java:39) 
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at com.lazylibs.component.ui.fragment.BaseSupportDialogFragment.onCreateView(BaseSupportDialogFragment.java:35) 

很多都是未能创建的，然后color这些都没用用上对应的皮肤 怎么解决这个问题。

**Comment by CoderAlee** [comment]
1. 如果View需要换肤的属性为TextColor、background这类原生属性可以通过一下方式将View创建出来
> `
ThemeSkinService.getInstance().getCreateViewInterceptor().add(new ConstraintLayoutFactory());
final class ConstraintLayoutFactory implements IExpandedFactory2 {
    /**
     * {@link ConstraintLayout} 类名
     */
    private final static String CLASS_NAME = ConstraintLayout.class.getName();

    /**
     * 创建View
     *
     * @param originalView 上一个IExpandedFactory生成的View
     * @param parent       父View
     * @param name         名称
     * @param context      {@link Context}
     * @param attrs        {@link AttributeSet}
     * @return 生成的View
     */
    @NonNull
    @Override
    public View onCreateView(@Nullable View originalView, @Nullable View parent, @NonNull String name, @NonNull Context context, @NonNull AttributeSet attrs) {
        return TextUtils.equals(CLASS_NAME, name) ? new ConstraintLayout(context, attrs) : originalView;
    }
}`
核心API为 hemeSkinService.getInstance().getCreateViewInterceptor().add(View)、IExpandedFactory2

2. 如果需要换肤的属性为自定义属性或框架内目前暂未实现的属性，需要按照**自定义View、三方库View换肤**的流程进行适配

**Comment by zhongcg** [comment]
解决了！感谢大佬，加了之后可以适配了， 但还是会出现很多这些log
未能成功创建 [ androidx.constraintlayout.widget.ConstraintLayout ]
未能成功创建 [ androidx.appcompat.widget.AppCompatTextView ]
未能成功创建 [ View ] 
未能成功创建 [ androidx.appcompat.widget.AppCompatTextView ]

**Comment by CoderAlee** [comment]
> 解决了！感谢大佬，加了之后可以适配了， 但还是会出现很多这些log 未能成功创建 [ androidx.constraintlayout.widget.ConstraintLayout ] 未能成功创建 [ androidx.appcompat.widget.AppCompatTextView ] 未能成功创建 [ View ] 未能成功创建 [ androidx.appcompat.widget.AppCompatTextView ]

这些日志是框架内的ViewInflater未能通过构默认构造函数创建出对应View的实例，并不代表最终View没有创建。比如`androidx.constraintlayout.widget.ConstraintLayout` 就是由`com.github.CoderAlee.PaintedSkin:constraintlayout-compat:TAG` 包提供的创建支持。
如果想忽略这些日志可以通过`Config.getInstance().setEnableDebugMode(false)` 来限制框架内日志的输出
