### ISSUE TITLE
demo报错

### ISSUE THREAD

**Issue by lexluthors** [CoderAlee/PaintedSkin#2]
java.lang.RuntimeException: Unable to create application org.alee.demo.skin.App: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.alee.reflex.ReflexBoolean.set(java.lang.Object, boolean)' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6652)
        at android.app.ActivityThread.access$1600(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.alee.reflex.ReflexBoolean.set(java.lang.Object, boolean)' on a null object reference
        at org.alee.component.skin.page.BaseWindowProxy.bindLayoutInflateFactory2(BaseWindowProxy.java:42)
        at org.alee.component.skin.page.GlobalWindowProxy.bindLayoutInflate(GlobalWindowProxy.java:19)
        at org.alee.component.skin.page.WindowManager.onAttachWindow(WindowManager.java:63)
        at org.alee.component.skin.page.WindowManager.init(WindowManager.java:54)
        at org.alee.component.skin.page.ApplicationHook.onCreateProcessor(ApplicationHook.java:40)
        at org.alee.demo.skin.App.onCreate(App.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6647)
        at android.app.ActivityThread.access$1600(ActivityThread.java:231) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by CoderAlee** [comment]
你好，请问你运行Demo的Android设备版本是多少？

**Comment by lexluthors** [comment]
> 你好，请问你运行Demo的Android设备版本是多少？

我的手机是一加6 android10.0  还有一个模拟器是11版本都是这个错误

**Comment by CoderAlee** [comment]
![image](https://user-images.githubusercontent.com/71973440/119925212-9084d480-bfa7-11eb-960b-f28472112409.png)
是由于Andorid P开始LayoutInflater 中的mFactorySet被@UnsupportedAppUsage注解保护起来导致无法反射获取。
建议先使用AndroidP版本一下的设备运行Demo。
此问题会优先修复

**Comment by CoderAlee** [comment]
3.1.8版本已支持在Android Q及以上版本的设备上运行
