### ISSUE TITLE
进入/退出节日模式,不重启的后果

### ISSUE THREAD

**Issue by jzllovecat** [CoderAlee/PaintedSkin#50]
以demo为例,进入/退出节日模式,不调用relaunchApp(),而是立即切一次皮肤
val defaultMode = KEY_THEME.loadInt(SkinOptionFactory.MODE_DEFAULT)
ThemeSkinService.getInstance().switchThemeSkin(defaultMode)
大多数情况下可以无缝切换,较少情况会切换到其他模式,比如当前是dark,切到了day
这不是重点
重点是,,不重启,开关系统的深色模式,会崩溃

FATAL EXCEPTION: main
                                                                                                    Process: org.alee.demo.skin, PID: 2445
                                                                                                    java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.google.android.material.button.MaterialButton$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/btn_open_festival_mode. Make sure other views do not use the same id.
                                                                                                    	at android.view.View.onRestoreInstanceState(View.java:21105)
                                                                                                    	at android.widget.TextView.onRestoreInstanceState(TextView.java:6037)
                                                                                                    	at android.view.View.dispatchRestoreInstanceState(View.java:21077)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
                                                                                                    	at android.view.View.restoreHierarchyState(View.java:21055)
                                                                                                    	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:639)
                                                                                                    	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3010)
                                                                                                    	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3001)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
                                                                                                    	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3002)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1473)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8079)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3761)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8022)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1091)

**Comment by CoderAlee** [comment]
> 以demo为例,进入/退出节日模式,不调用relaunchApp(),而是立即切一次皮肤 val defaultMode = KEY_THEME.loadInt(SkinOptionFactory.MODE_DEFAULT) ThemeSkinService.getInstance().switchThemeSkin(defaultMode) 大多数情况下可以无缝切换,较少情况会切换到其他模式,比如当前是dark,切到了day 这不是重点 重点是,,不重启,开关系统的深色模式,会崩溃
> 
> FATAL EXCEPTION: main Process: org.alee.demo.skin, PID: 2445 java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.google.android.material.button.MaterialButton$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/btn_open_festival_mode. Make sure other views do not use the same id. at android.view.View.onRestoreInstanceState(View.java:21105) at android.widget.TextView.onRestoreInstanceState(TextView.java:6037) at android.view.View.dispatchRestoreInstanceState(View.java:21077) at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006) at android.view.View.restoreHierarchyState(View.java:21055) at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:639) at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3010) at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3001) at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580) at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285) at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112) at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647) at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128) at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072) at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3002) at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580) at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285) at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112) at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647) at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128) at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072) at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251) at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502) at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246) at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1473) at android.app.Activity.performStart(Activity.java:8079) at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3761) at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:8022) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1091)

根据异常信息提示，出现异常的根源是你的ViewTree中有相同id的View所以引发了此问题，请先排查viewtree中的view id分配是否合理

**Comment by jzllovecat** [comment]
运行的是你的工程里的demo,btn_open_festival_mode这个id只有开启节日模式按钮使用,没有别的view使用,应该是系统的切换深色模式导致fragment重建而前面的fragment没有销毁

**Comment by CoderAlee** [comment]
> 运行的是你的工程里的demo,btn_open_festival_mode这个id只有开启节日模式按钮使用,没有别的view使用,应该是系统的切换深色模式导致fragment重建而前面的fragment没有销毁

Demo工程在Fragment中有缓存根View，以避免每次都重新onCreateView,是会有这个问题的。
